#!/bin/sh

MATCH="^[[:space:]]*($|;)"

echo "==== Additional PHP 8.3 information ====" >&3
echo "" >&3
echo "++++ PHP 8.3 SAPI (php8.3query -S): ++++" >&3
/usr/sbin/php8.3query -S >&3
echo "" >&3
echo "++++ PHP 8.3 Extensions (php8.3query -M -v): ++++" >&3
/usr/sbin/php8.3query -M -v >&3
echo "" >&3

echo "++++ Configuration files: ++++" >&3
"**** /etc/php/8.3/cli/php.ini ****" >&3
grep -Ev "$MATCH" /etc/php/8.3/cli/php.ini >&3
echo "" >&3
find /etc/php/8.3/cli/conf.d/ -name '*.ini' | \
while read CONF; do
    echo "**** $CONF ****" >&3
    grep -Ev "$MATCH" "$CONF" >&3
    echo "" >&3
done
